// taiwan-hua.js — 台湾華語の語彙問題（例外的な組み込み科目）
// CSV（単語・ピンイン・日本語）から生成。単語＋ピンインを出題し、日本語を4択で選ぶ。
const TAIWAN_HUA_QUESTIONS = [
  { question: "熱（rè）", answer: "熱い / 暑い" },
  { question: "冷（lěng）", answer: "冷たい / 寒い" },
  { question: "冰（bīng）", answer: "氷のように冷たい" },
  { question: "溫（wēn）", answer: "ぬるい / 温かい" },
  { question: "辣（là）", answer: "辛い" },
  { question: "甜（tián）", answer: "甘い" },
  { question: "酸（suān）", answer: "酸っぱい" },
  { question: "鹹（xián）", answer: "塩辛い / しょっぱい" },
  { question: "苦（kǔ）", answer: "苦い" },
  { question: "好吃（hǎo chī）", answer: "（食べ物が）美味しい" },
  { question: "好喝（hǎo hē）", answer: "（飲み物が）美味しい" },
  { question: "貴（guì）", answer: "（値段が）高い" },
  { question: "便宜（pián yi）", answer: "安い" },
  { question: "多（duō）", answer: "多い" },
  { question: "少（shǎo）", answer: "少ない" },
  { question: "大（dà）", answer: "大きい" },
  { question: "小（xiǎo）", answer: "小さい" },
  { question: "高（gāo）", answer: "高い" },
  { question: "矮（ǎi）", answer: "（背が）低い" },
  { question: "遠（yuǎn）", answer: "遠い" },
  { question: "近（jìn）", answer: "近い" },
  { question: "累（lèi）", answer: "疲れた" },
  { question: "快樂（kuài lè）", answer: "楽しい / 幸せな" },
  { question: "高興（gāo xìng）", answer: "嬉しい" },
  { question: "漂亮（piào liang）", answer: "美しい / 綺麗な" },
  { question: "乾淨（gān jìng）", answer: "清潔な / 綺麗な" },
  { question: "髒（zāng）", answer: "汚い" },
  { question: "忙（máng）", answer: "忙しい" },
  { question: "新鮮（xīn xiān）", answer: "新鮮な" },
  { question: "飽（bǎo）", answer: "お腹がいっぱい" },
  { question: "你好（nǐ hǎo）", answer: "こんにちは" },
  { question: "早安（zǎo ān）", answer: "おはよう" },
  { question: "午安（wǔ ān）", answer: "こんにちは（昼・午後）" },
  { question: "晚安（wǎn ān）", answer: "おやすみなさい" },
  { question: "再見（zài jiàn）", answer: "さようなら" },
  { question: "拜拜（bái bái）", answer: "バイバイ（別れ際の挨拶）" },
  { question: "明天見（míng tiān jiàn）", answer: "また明日" },
  { question: "謝謝（xiè xie）", answer: "ありがとう" },
  { question: "不客氣（bú kè qì）", answer: "どういたしまして" },
  { question: "對不起（duì bù qǐ）", answer: "ごめんなさい" },
  { question: "沒關係（méi guān xì）", answer: "大丈夫です / 気にしないで" },
  { question: "不好意思（bù hǎo yì si）", answer: "すみません（呼びかけ、軽い謝罪や感謝）" },
  { question: "請問（qǐng wèn）", answer: "お尋ねしますが / すみません" },
  { question: "吃飽了沒？（chī bǎo le méi）", answer: "ご飯食べた？（台湾定番の挨拶）" },
  { question: "吃飽了（chī bǎo le）", answer: "食べました / お腹いっぱいです" },
  { question: "好久不見（hǎo jiǔ bú jiàn）", answer: "お久しぶりです" },
  { question: "你好嗎？（nǐ hǎo ma）", answer: "お元気ですか？" },
  { question: "很高興認識你（hěn gāo xìng rèn shi nǐ）", answer: "お会いできて嬉しいです" },
  { question: "請多指教（qǐng duō zhǐ jiào）", answer: "よろしくお願いします" },
  { question: "辛苦了（xīn kǔ le）", answer: "お疲れ様でした" },
  { question: "歡迎光臨（huān yíng guāng lín）", answer: "いらっしゃいませ" },
  { question: "慢走（màn zǒu）", answer: "お気をつけて（見送る側の挨拶）" },
  { question: "保重（bǎo zhòng）", answer: "お大事に / お体に気をつけて" },
  { question: "恭喜（gōng xǐ）", answer: "おめでとう" },
  { question: "生日快樂（shēng rì kuài lè）", answer: "誕生日おめでとう" },
  { question: "新年快樂（xīn nián kuài lè）", answer: "新年あけましておめでとう" },
  { question: "祝你好運（zhù nǐ hǎo yùn）", answer: "幸運を祈ります / がんばって" },
  { question: "乾杯（gān bēi）", answer: "乾杯" },
  { question: "沒問題（méi wèn tí）", answer: "問題ありません / 大丈夫です" },
  { question: "麻煩你了（má fán nǐ le）", answer: "お手数をおかけします / よろしくお願いします" },
  { question: "珍珠奶茶（zhēn zhū nǎi chá）", answer: "タピオカミルクティー" },
  { question: "雞排（jī pái）", answer: "台湾風大判フライドチキン" },
  { question: "臭豆腐（chòu dòu fǔ）", answer: "臭豆腐" },
  { question: "蚵仔煎（é zǐ jiān）", answer: "牡蠣オムレツ" },
  { question: "大腸包小腸（dà cháng bāo xiǎo cháng）", answer: "台湾風ライスホットドッグ" },
  { question: "滷肉飯（lǔ ròu fàn）", answer: "ルーローハン（豚肉そぼろご飯）" },
  { question: "地瓜球（dì guā qiú）", answer: "さつまいもボール" },
  { question: "芒果冰（máng guǒ bīng）", answer: "マンゴーかき氷" },
  { question: "鹽酥雞（yán sū jī）", answer: "台湾風ポップコーンチキン" },
  { question: "水煎包（shuǐ jiān bāo）", answer: "焼き肉まん" },
  { question: "蔥抓餅（cōng zhuā bǐng）", answer: "台湾風ネギパイ" },
  { question: "烤肉串（kǎo ròu chuàn）", answer: "焼き串" },
  { question: "糖葫蘆（táng hú lu）", answer: "フルーツ飴" },
  { question: "豆花（dòu huā）", answer: "トウファ（大豆ゼリースイーツ）" },
  { question: "牛肉麵（niú ròu miàn）", answer: "牛肉麺" },
  { question: "刈包（guà bāo）", answer: "台湾風角煮バーガー" },
  { question: "胡椒餅（hú jiāo bǐng）", answer: "胡椒餅" },
  { question: "木瓜牛奶（mù guā niú nǎi）", answer: "パパイヤミルク" },
  { question: "烤玉米（kǎo yù mǐ）", answer: "焼きトウモロコシ" },
  { question: "潤餅（rùn bǐng）", answer: "台湾風生春巻き" },
  { question: "麵線（miàn xiàn）", answer: "台湾風そうめん" },
  { question: "豬血糕（zhū xiě gāo）", answer: "豚の血ともち米の蒸し物" },
  { question: "烤魷魚（kǎo yóu yú）", answer: "イカ焼き" },
  { question: "生煎包（shēng jiān bāo）", answer: "焼き小籠包" },
  { question: "愛玉冰（ài yù bīng）", answer: "オーギョーチ（愛玉ゼリー）" },
  { question: "芋圓（yù yuán）", answer: "タロ芋ボール" },
  { question: "蛋餅（dàn bǐng）", answer: "ダンピン（台湾風卵クレープ）" },
  { question: "燒仙草（shāo xiān cǎo）", answer: "ホット仙草ゼリー" },
  { question: "小籠包（xiǎo lóng bāo）", answer: "小籠包" },
  { question: "冬瓜茶（dōng guā chá）", answer: "トウガン茶" },
  { question: "護照（hù zhào）", answer: "パスポート" },
  { question: "簽證（qiān zhèng）", answer: "ビザ" },
  { question: "機票（jī piào）", answer: "航空券" },
  { question: "登機證（dēng jī zhèng）", answer: "搭乗券" },
  { question: "入境卡（rù jìng kǎ）", answer: "入国カード" },
  { question: "行李（xíng lǐ）", answer: "荷物" },
  { question: "隨身行李（suí shēn xíng lǐ）", answer: "機内持ち込み荷物" },
  { question: "托運行李（tuō yùn xíng lǐ）", answer: "預け入れ荷物" },
  { question: "航廈（háng xià）", answer: "ターミナル（空港の）" },
  { question: "海關（hǎi guān）", answer: "税関" },
  { question: "入境審查（rù jìng shěn chá）", answer: "入国審査" },
  { question: "觀光（guān guāng）", answer: "観光" },
  { question: "飯店（fàn diàn）", answer: "ホテル" },
  { question: "民宿（mín sù）", answer: "民宿 / ゲストハウス" },
  { question: "辦理入住（bàn lǐ rù zhù）", answer: "チェックイン（手続き）" },
  { question: "退房（tuì fáng）", answer: "チェックアウト" },
  { question: "櫃檯（guì tái）", answer: "フロント / カウンター" },
  { question: "房卡（fáng kǎ）", answer: "ルームキー / ドアカード" },
  { question: "訂房（dìng fáng）", answer: "ホテルの予約" },
  { question: "單人房（dān rén fáng）", answer: "シングルルーム" },
  { question: "雙人房（shuāng rén fáng）", answer: "ダブルルーム / ツインルーム" },
  { question: "早餐（zǎo cān）", answer: "朝食" },
  { question: "無線網路（wú xiàn wǎng lù）", answer: "Wi-Fi / ワイヤレスネットワーク" },
  { question: "密碼（mì mǎ）", answer: "パスワード" },
  { question: "寄放行李（jì fàng xíng lǐ）", answer: "荷物の預かり / 荷物を預ける" },
  { question: "轉機（zhuǎn jī）", answer: "乗り継ぎ / トランジット" },
  { question: "申報（shēn bào）", answer: "申告" },
  { question: "外幣兌換（wài bì duì huàn）", answer: "外貨両替" },
  { question: "計程車（jì chéng chē）", answer: "タクシー" },
  { question: "捷運（jié yùn）", answer: "MRT（台湾の都市鉄道）" },
];
